class FutureProperty {
  String propertyPhoto;
  String locations;
  String flatNumber;
  String buyRent;
  String residenceCommercial;
  String apartmentName;
  String apartmentAddress;
  String typeOfProperty;
  String bhk;
  String showPrice;
  String lastPrice;
  String askingPrice;
  String floor;
  String totalFloor;
  String balcony;
  String squarefit;
  String maintance;
  String parking;
  String ageOfProperty;
  String fieldworkarAddress;
  String roadSize;
  String metroDistance;
  String highwayDistance;
  String mainMarketDistance;
  String meter;
  String ownerName;
  String ownerNumber;
  String currentDate;
  String availableDate;
  String kitchen;
  String bathroom;
  String lift;
  String facility;
  String furnished;
  String fieldWorkerName;
  String liveUnlive;
  String fieldWorkerNumber;
  String registryAndGpa;
  String loan;
  String longitude;
  String latitude;

  FutureProperty({
    required this.propertyPhoto,
    required this.locations,
    required this.flatNumber,
    required this.buyRent,
    required this.residenceCommercial,
    required this.apartmentName,
    required this.apartmentAddress,
    required this.typeOfProperty,
    required this.bhk,
    required this.showPrice,
    required this.lastPrice,
    required this.askingPrice,
    required this.floor,
    required this.totalFloor,
    required this.balcony,
    required this.squarefit,
    required this.maintance,
    required this.parking,
    required this.ageOfProperty,
    required this.fieldworkarAddress,
    required this.roadSize,
    required this.metroDistance,
    required this.highwayDistance,
    required this.mainMarketDistance,
    required this.meter,
    required this.ownerName,
    required this.ownerNumber,
    required this.currentDate,
    required this.availableDate,
    required this.kitchen,
    required this.bathroom,
    required this.lift,
    required this.facility,
    required this.furnished,
    required this.fieldWorkerName,
    required this.liveUnlive,
    required this.fieldWorkerNumber,
    required this.registryAndGpa,
    required this.loan,
    required this.longitude,
    required this.latitude,
  });

  Map<String, dynamic> toJson() => {
    "property_photo": propertyPhoto,
    "locations": locations,
    "Flat_number": flatNumber,
    "Buy_Rent": buyRent,
    "Residence_Commercial": residenceCommercial,
    "Apartment_name": apartmentName,
    "Apartment_Address": apartmentAddress,
    "Typeofproperty": typeOfProperty,
    "Bhk": bhk,
    "show_Price": showPrice,
    "Last_Price": lastPrice,
    "asking_price": askingPrice,
    "Floor_": floor,
    "Total_floor": totalFloor,
    "Balcony": balcony,
    "squarefit": squarefit,
    "maintance": maintance,
    "parking": parking,
    "age_of_property": ageOfProperty,
    "fieldworkar_address": fieldworkarAddress,
    "Road_Size": roadSize,
    "metro_distance": metroDistance,
    "highway_distance": highwayDistance,
    "main_market_distance": mainMarketDistance,
    "meter": meter,
    "owner_name": ownerName,
    "owner_number": ownerNumber,
    "current_dates": currentDate,
    "available_date": availableDate,
    "kitchen": kitchen,
    "bathroom": bathroom,
    "lift": lift,
    "Facility": facility,
    "furnished_unfurnished": furnished,
    "field_warkar_name": fieldWorkerName,
    "live_unlive": liveUnlive,
    "field_workar_number": fieldWorkerNumber,
    "registry_and_gpa": registryAndGpa,
    "loan": loan,
    "Longitude": longitude,
    "Latitude": latitude,
  };
}
